name: llp_flutter_learning_app
description: "Flutter learning app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  widget_with_codeview: ^3.1.0
  cupertino_icons: ^1.0.6
  badges: ^3.1.2
  flutter_slidable: ^3.1.1
  backdrop: ^0.9.1
  convex_bottom_bar: ^3.2.0
  hidable: ^1.0.6
  intl: ^0.19.0
  provider: ^6.1.2
  http: ^1.2.2
  firebase_core: ^2.24.2
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/widgets/
    - lib/appbars/
    - lib/layouts/
    - lib/navigations/
    - lib/lists/
    - assets/images/
