// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACIrZzo89L1h4DPXsJc1FIB5Ebb8XzUfQ',
    appId: '1:524725915609:web:212e081736540a3ab593c8',
    messagingSenderId: '524725915609',
    projectId: 'llp-firebase-test',
    authDomain: 'llp-firebase-test.firebaseapp.com',
    storageBucket: 'llp-firebase-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2zwhgh_YSZ5MLSa2IA4GcaQ2XEwdhpA4',
    appId: '1:524725915609:android:cba197fad65c815bb593c8',
    messagingSenderId: '524725915609',
    projectId: 'llp-firebase-test',
    storageBucket: 'llp-firebase-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb-a3mWEHx11zzTzeoXgW3UJf1EjGYEJA',
    appId: '1:524725915609:ios:6ccbaba60897632db593c8',
    messagingSenderId: '524725915609',
    projectId: 'llp-firebase-test',
    storageBucket: 'llp-firebase-test.appspot.com',
    iosBundleId: 'com.mmk.llpFlutterLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb-a3mWEHx11zzTzeoXgW3UJf1EjGYEJA',
    appId: '1:524725915609:ios:6ccbaba60897632db593c8',
    messagingSenderId: '524725915609',
    projectId: 'llp-firebase-test',
    storageBucket: 'llp-firebase-test.appspot.com',
    iosBundleId: 'com.mmk.llpFlutterLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACIrZzo89L1h4DPXsJc1FIB5Ebb8XzUfQ',
    appId: '1:524725915609:web:3c95c7b033e002dbb593c8',
    messagingSenderId: '524725915609',
    projectId: 'llp-firebase-test',
    authDomain: 'llp-firebase-test.firebaseapp.com',
    storageBucket: 'llp-firebase-test.appspot.com',
  );
}
